### ISSUE TITLE
大佬～能求一份比赛数据集吗？原来的数据集已经在官网下架了

### ISSUE THREAD

**Issue by Vanly233** [xueyouluo/ccks2021-track2-code#1]
大佬～能求一份比赛数据集吗？原来的数据集已经在官网下架了，vanly233@163.com 谢谢大佬

**Comment by xueyouluo** [comment]
已发，其实可以试试这个 https://tianchi.aliyun.com/dataset/dataDetail?dataId=109339。

**Comment by Vanly233** [comment]
谢谢大佬～已收到～
