### ISSUE TITLE
大佬你好啊~我不太理解github主页的实验中，实验8：biaffine+bert+electra 为什么两个预训练模型，他们分别的作用是啥？还是说把两个预训练模型

### ISSUE THREAD

**Issue by maochunyan1218** [xueyouluo/ccks2021-track2-code#4]
大佬你好啊~我不太理解github主页的实验中，实验8：biaffine+bert+electra 为什么两个预训练模型，他们分别的作用是啥？

是把两个预训练模型融合成一个预训练模型的意思么？

另外electra pretain 是指用自己的数据重新预训练了一下吗？
感谢

**Comment by xueyouluo** [comment]
这个应该在群里回复过了。

8 - 是指把bert换成了electra
electra-pretrain是指用任务数据进行预训练了electra
