### ISSUE TITLE
assemble_fake()出错

### ISSUE THREAD

**Issue by chenlala-a** [xueyouluo/ccks2021-track2-code#6]
您好~请问一下我再运行您代码的时候
在code/assemble.py里
assert len(data[0)==len(weights)出现了AssertionError的错误，请问您了解解决方案吗，或者具体是哪里出的问题呢

**Comment by wuchenghao0215** [comment]
你好，我也遇到了这个问题，我的解决办法是将 electra_180g_base.zip 的解压路径设置为 user_data/electra/electra_180g_base/，而不是 user_data/electra/
